# H2M Tutorial
Author: Kexin Dong  
Date: Jan 4, 2024

H2M is a python package for precise modeling of human vairants in mice.

# Quick Start

## Installation

In [ ]:
pip install h2m

## Importing packages

In [105]:
import h2m
import pandas as pd

## Loading data  
We should upload reference genome and GENCODE annotation data for both human and mouse, which could be directly downloaded from a public [dropbox](https://www.dropbox.com/scl/fo/1wtrnc9w6s9gemweuw2fv/h?rlkey=hli1z6tv096cjwit5oi6bwggg&dl=0) (**Gencode** and **Refgenome** fold respectively).  
Both GRCh37 and GRCh38 human reference genome assemblys are available. Upload the one that you are going to use.

In [106]:
path_h_ref, path_m_ref = '/Users/gorkordkx/Documents/Database/RefGenome/ncbi-2023-09-12/GCF_000001405.25_GRCh37.p13_genomic.fna.gz', '/Users/gorkordkx/Documents/Database/RefGenome/mouse-2023-09-13/GCF_000001635.27_GRCm39_genomic.fna.gz'
# remember to replace the paths with yours
records_h, index_list_h = h2m.genome_loader(path_h_ref)
records_m, index_list_m  = h2m.genome_loader(path_m_ref)

path_h_anno, path_m_anno = '/Users/gorkordkx/Documents/Database/Genecode/gencode_v19_GRCh37.db', '/Users/gorkordkx/Documents/Database/Genecode/gencode_vm33_GRCm39.db'
# remember to replace the paths with yours
db_h, db_m = h2m.anno_loader(path_h_anno), h2m.anno_loader(path_m_anno)

It may take up to 3 minutes to load the ref genomes.

A notebook file about how to generate the db file: [1_prepare_gencode_annotation_file.ipynb]('1_prepare_gencode_annotation_file.ipynb')

## Query mouse orthologous genes
First of all, you can use H2M to query a human gene for the presence of mouse homologs.

In [3]:
query_result = h2m.query('TP53')

Query human gene: TP53;
Mouse ortholog(s): Trp53;
Homology type: one2one;
Sequence Simalarity(%):77.3537.

The output is a list of information for all the mouse ortholog(s) (if have; sometimes more than one).  
Each element is a dictionary of **mouse gene name**, **mouse gene id**, **homology type** (one to one/one to multiple/many to many), and **similarity of human and mouse gene in percentage**.

In [4]:
h2m.query('U1')

Query human gene: U1;
Mouse ortholog(s): Gm24251,Gm24291,Gm24251;
Homology type: one2many;
Sequence Simalarity(%):50.0, 59.6591, 50.6944.

[{'gene_name_m': 'Gm24251',
  'gene_id_m': 'ENSMUSG00000087949',
  'homology_type': 'ortholog_one2many',
  'similarity': 50.0},
 {'gene_name_m': 'Gm24291',
  'gene_id_m': 'ENSMUSG00000088258',
  'homology_type': 'ortholog_one2many',
  'similarity': 59.6591},
 {'gene_name_m': 'Gm24251',
  'gene_id_m': 'ENSMUSG00000087949',
  'homology_type': 'ortholog_one2many',
  'similarity': 50.6944}]

In [5]:
h2m.query('TPT1P6')

Class 7: The query human gene: TPT1P6 has no mouse ortholog.

[None]

A print output is helpful in interactive tasks like a Jupyter Notebook. You can also turn off this.

In [6]:
h2m.query('UBAC2', show = False)

[{'gene_name_m': 'Ubac2',
  'gene_id_m': 'ENSMUSG00000041765',
  'homology_type': 'ortholog_one2one',
  'similarity': 89.2442}]

Except for gene names, both ENSEMBL gene id and transcript id are accepted to identify a human gene. You can use the **ty** parameter ('tx_id','gene_id' or 'name') to specify your input type, but this is totally optional.

Using gene id:

In [7]:
query_result = h2m.query('ENSG00000141510')

Query human gene: TP53;
Mouse ortholog(s): Trp53;
Homology type: one2one;
Sequence Simalarity(%):77.3537.

Using transcript id. Should include a db annotation file with the same ref genome version.

In [8]:
query_result = h2m.query('ENST00000269305.4', db=db_h, ty='tx_id')

Query human gene: TP53;
Mouse ortholog(s): Trp53;
Homology type: one2one;
Sequence Simalarity(%):77.3537.

The query result of all human genes, as well as corresponding transcript IDs, is also available as [a csv file]('https://www.dropbox.com/scl/fi/o6735wok25t5dstvpz9kd/Supp_Table_1_Homo_Genes.csv?rlkey=skvxlcfv4r8ksspiq5itxxjc9&dl=0').

## Get transcript ID (Internet connection needed)

One gene may have different transcripts. For mutation modeling, it is important to specify one transcript. If you do not have this information in hand, you can use H2M to get it.

Again, both gene IDs and gene names are accepted as identificaitons for human and mouse genes.

In [9]:
list_tx_id_h = h2m.get_tx_id('TP53', 'h', ver=37)

Genome assembly: GRCh37;
The canonical transcript is: ENST00000269305.4;
You can choose from the 17 transcripts below for further analysis:
(1)ENST00000269305.4 (2)ENST00000413465.2 (3)ENST00000359597.4 (4)ENST00000504290.1 (5)ENST00000510385.1 (6)ENST00000504937.1 (7)ENST00000455263.2 (8)ENST00000420246.2 (9)ENST00000445888.2 (10)ENST00000576024.1 (11)ENST00000509690.1 (12)ENST00000514944.1 (13)ENST00000574684.1 (14)ENST00000505014.1 (15)ENST00000508793.1 (16)ENST00000604348.1 (17)ENST00000503591.1

In [10]:
list_tx_id_m = h2m.get_tx_id('ENSMUSG00000059552', 'm')

Genome assembly: GRCm39;
The canonical transcript is: ENSMUST00000108658.10;
You can choose from the 6 transcripts below for further analysis:
(1)ENSMUST00000108658.10 (2)ENSMUST00000171247.8 (3)ENSMUST00000005371.12 (4)ENSMUST00000147512.2 (5)ENSMUST00000108657.4 (6)ENSMUST00000130540.2

More information is offered except for a complete list of all transcripts.

- the chromosome

In [11]:
list_tx_id_h[0]

17

- the start and end location of the gene on the chromosome

In [12]:
list_tx_id_h[1:3]

[7565097, 7590856]

- the canonical transcript annotated by ENSEMBL database and used by major clinical datasets (e.g. AACR-GENIE)

In [13]:
list_tx_id_h[3]

'ENST00000269305.4'

- the complete list of transcripts starting with the canonical one

In [14]:
list_tx_id_h[4]

['ENST00000269305.4',
 'ENST00000413465.2',
 'ENST00000359597.4',
 'ENST00000504290.1',
 'ENST00000510385.1',
 'ENST00000504937.1',
 'ENST00000455263.2',
 'ENST00000420246.2',
 'ENST00000445888.2',
 'ENST00000576024.1',
 'ENST00000509690.1',
 'ENST00000514944.1',
 'ENST00000574684.1',
 'ENST00000505014.1',
 'ENST00000508793.1',
 'ENST00000604348.1',
 'ENST00000503591.1']

The output is a list of information for all the mouse ortholog(s) (if have; sometimes more than one).  
Each element is a dictionary of **mouse gene name**, **mouse gene id**, **homology type** (one to one/one to multiple), and **similarity of human and mouse gene in percentage**.

## Modeling human variants in the mouse genome

### Input

Now you can use H2M to model your human mutations of interest.  
You should have at least such information in hand:  
1. transcript id of the human gene
2. transcript id of the mouse gene
3. start location of human variants *on the chromosome*  
4. end location of human variants *on the chromosome*  
5. the reference and alternative sequence *on the positive strand of the chromosome*  
6. mutation type (**str in ['SNP','DNP','ONP','INS','DEL'])
7. the version number of human ref genome

Usually, such information has been pretty well organized in different databases and is easy to get.

### Usage

Taking *TP53* R273H (ENST00000269305.4:c.818G>A) as an example.

In [15]:
tx_id_h, tx_id_m = list_tx_id_h[3], list_tx_id_m[3]
# use the canonical transcript

In [16]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577120, 7577120, 'C','T', ty_h = 'SNP', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577120,7577120,C,T,ENST00000269305.4:c.817G>A,R273H,Missense,E_7,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_7,69480434,69480434,G,A,ENSMUST00000108658.10:c.808G>A,R270H,69480434,69480434,G,A,ENSMUST00000108658.10:c.808G>A,R270H

Another non-coding example.

In [17]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7578291,7578291, 'T','G', ty_h = 'SNP', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578291,7578291,T,G,ENST00000269305.4:c.263A>C,None,"Non_Coding,I",None,SNP,True,2,"Class 2: This mutation can be modeled, but the...",Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Intron,None,69479450,69479450,A,C,ENSMUST00000108658.10:c.260A>C,None,69479450,69479450,A,C,ENSMUST00000108658.10:c.260A>C,None

We can see that this human mutaton can be originally modeled by introducing the same neucleotide alteration.

By setting **show_sequence = True**, we can output the sequences of the wild-type and mutated human gene, wild-type, originally-modeled, and alternatively-modeled (if exsist) mouse gene. (If it can be originally modeled, the new_seq_m_alt would be the same as new_seq_m_ori)

In [18]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577120, 7577120, 'C','T', ty_h = 'SNP', ver = 37, show_sequence=True)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m,seq_h,seq_m,new_seq_h,new_seq_m_ori,new_seq_m_alt,human_idx,mouse_idx
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577120,7577120,C,T,ENST00000269305.4:c.817G>A,R273H,Missense,E_7,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_7,69480434,69480434,G,A,ENSMUST00000108658.10:c.808G>A,R270H,69480434,69480434,G,A,ENSMUST00000108658.10:c.808G>A,R270H,"(A, T, G, G, A, G, G, A, G, C, C, G, C, A, G, ...","(A, T, G, A, C, T, G, C, C, A, T, G, G, A, G, ...","(A, T, G, G, A, G, G, A, G, C, C, G, C, A, G, ...","(A, T, G, A, C, T, G, C, C, A, T, G, G, A, G, ...","(A, T, G, A, C, T, G, C, C, A, T, G, G, A, G, ...",817,808

In [19]:
seq_h, seq_m, new_seq_h, new_seq_m = model_result[0]['seq_h'], model_result[0]['seq_m'], model_result[0]['new_seq_h'],  model_result[0]['new_seq_m_ori']

Sometimes the mutation does not locate in the homologous region. Taking *TP53* D393Y as an example.

In [20]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7572932, 7572932, 'C','A', ty_h = 'SNP', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7572932,7572932,C,A,ENST00000269305.4:c.1176G>T,D393Y,Missense,E_10,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

Flanked size is a parameter that controls how many amino acids (or neucleotides, for non-coding mutations) are included on both sides of the mutated region. You can change that by parameter **flank_size**.

In [21]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7572932, 7572932, 'C','A', ty_h = 'SNP', ver = 37, flank_size=1)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7572932,7572932,C,A,ENST00000269305.4:c.1176G>T,D393Y,Missense,E_10,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_10,69482252,69482252,G,T,ENSMUST00000108658.10:c.1167G>T,D390Y,69482252,69482252,G,T,ENSMUST00000108658.10:c.1167G>T,D390Y

With the flank size of 1 (which means 3 amino acids are taken into consideration in totall), this mutation can be originally modeled.

### Alternative modeling

Sometimes the human mutation cannot be originally modeled in the mouse genome by using the same neucleotide alteration. Under this circumsatance, some alternative modeling strategies may be found by searching the codon list of the target amino acids. Taking TP53 R249_T253delinsS as an example.

In [23]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577523, 7577534, 'GTGAGGATGGGC', '-', ty_h = 'DEL', ver = 37)

The default maximum number of output alternatives is 5. You can definitly change that by the parameter **max_alternative**.

In [24]:
model_result_long = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577523, 7577534, 'GTGAGGATGGGC', '-', ty_h = 'DEL', ver = 37, max_alternative=10)
len(model_result), len(model_result_long)

(5, 6)

If you do not want to alternatively model variants, you can set **search_alternatve** to False.

In [25]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577523, 7577534, 'GTGAGGATGGGC', '-', ty_h = 'DEL', ver = 37, search_alternative= False)
model_result[0]['statement']

'Class 6: This mutation cannot be originally modeled and is awaiting alternative.'

### Original modeling with uncertain effects

For frame-shifting mutations and mutations in the non-coding region, we cannot find such alternative modeling strategies with the same protein change effects. H2M will only offer the original modeling and its effect.

- Example 1: *TP53* C275Lfs*31

In [26]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577115, 7577116, '','A', ty_h = 'INS', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577115,7577116,,A,ENST00000269305.4:c.821_822>T,C275Lfs*31,Frame_Shifting,E_7,INS,True,2,"Class 2: This mutation can be modeled, but the...",Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,INS,Frame_Shifting,E_7,69480438,69480439,,T,ENSMUST00000108658.10:c.812_813>T,C272Lfs*24,69480438,69480439,,T,ENSMUST00000108658.10:c.812_813>T,C272Lfs*24

In [27]:
p_h, p_m = model_result[0]['HGVSp_h'], model_result[0]['HGVSp_m']
print(f'HGVSp_h: {p_h}, HGVSp_m: {p_m}')

HGVSp_h: C275Lfs*31, HGVSp_m: C272Lfs*24

- Example 2: TP53 splice site mutation

In [28]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7578555, 7578555, 'C', 'T', ty_h = 'SNP', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578555,7578555,C,T,ENST00000269305.4:c.30G>A,None,"Non_Coding,I",None,SNP,True,2,"Class 2: This mutation can be modeled, but the...",Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Intron,None,69479189,69479189,G,A,ENSMUST00000108658.10:c.30G>A,None,69479189,69479189,G,A,ENSMUST00000108658.10:c.30G>A,None

### Additional function 1: modeling for base editing

When you set **param = 'BE'**, you will get modeling results that can be modeled by base editing (A->G, G->A, C->T, T->C, AA->GG, ...etc.). If one mutation can be originally modeled in the mouse genome but not in a BE style, alternative BE modeling strategies will be returned too.

Taking *KEAP1* F221L as an example.

In [29]:
h2m.query('KEAP1')

Query human gene: KEAP1;
Mouse ortholog(s): Keap1;
Homology type: one2one;
Sequence Simalarity(%):94.0705.

[{'gene_name_m': 'Keap1',
  'gene_id_m': 'ENSMUSG00000003308',
  'homology_type': 'ortholog_one2one',
  'similarity': 94.0705}]

In [30]:
tx_id_h_2, tx_id_m_2 = h2m.get_tx_id('KEAP1','h',ver=37, show=False)[3], h2m.get_tx_id('Keap1','m', show=False)[3]
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h_2, tx_id_m_2, 10602915, 10602915, 'G','T', ty_h = 'SNP', ver = 37, param='BE')
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,KEAP1,ENSG00000079999.9,ENST00000171111.5,chr19,5,-,True,10602915,10602915,G,T,ENST00000171111.5:c.662C>A,F221L,Missense,E_2,SNP,True,1,Class 1: This mutation can be alternatively mo...,Keap1,ENSMUSG00000003308.16,ENSMUST00000164812.8,chr9,5,-,SNP,Missense,E_2,21145346,21145346,G,T,ENSMUST00000164812.8:c.662C>A,F221L,21145348,21145348,A,G,ENSMUST00000164812.8:c.660T>C,F221L

### Additional function 2: modeling by amino acid change input

Set **coor = 'aa'** and modeling human variants by amino acid change input. Use TP53 R175H as an example.

In [31]:
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 175, 175, 'R', 'H', coor = 'aa', ty_h = 'SNP', ver = 37)
pd.DataFrame(model_result)

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578405,7578407,GCG,GTG,ENST00000269305.4:c.522_524CGC>CAC,R175H,Missense,E_4,SNP,True,1,Class 1: This mutation can be alternatively mo...,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_4,69479337,69479339,CGC,CAC,ENSMUST00000108658.10:c.513_515CGC>CAC,R172H,69479338,69479338,G,A,ENSMUST00000108658.10:c.514G>A,R172H
1,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578405,7578407,GCG,GTG,ENST00000269305.4:c.522_524CGC>CAC,R175H,Missense,E_4,SNP,True,1,Class 1: This mutation can be alternatively mo...,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,DNP,Missense,E_4,69479337,69479339,CGC,CAC,ENSMUST00000108658.10:c.513_515CGC>CAC,R172H,69479338,69479339,GC,AT,ENSMUST00000108658.10:c.514_515GC>AT,R172H

## Batch Processing

### Input format

In batch processing, you need to build a pandas dataframe with columns as the following example:

In [26]:
df_sample = pd.read_csv('input/sample_data.csv')
df_sample

,index,gene_name_h,tx_id_h,start_h,end_h,class_h,type_h,ref_seq_h,alt_seq_h
0,0,TP53,ENST00000269305.4,7579311,7579311,Splice_Site,SNP,C,A
1,1,KRAS,ENST00000256078.4,25398284,25398284,Missense_Mutation,SNP,C,A
2,2,TP53,ENST00000269305.4,7577567,7577567,Nonsense_Mutation,SNP,A,T
3,3,KRAS,ENST00000256078.4,25398284,25398284,Missense_Mutation,SNP,C,T
4,4,KRAS,ENST00000256078.4,25398281,25398281,Missense_Mutation,SNP,C,T
5,5,TP53,ENST00000269305.4,7578392,7578392,Missense_Mutation,SNP,C,T
6,6,TP53,ENST00000269305.4,7578406,7578406,Missense_Mutation,SNP,C,T
7,7,TP53,ENST00000269305.4,7577141,7577141,Missense_Mutation,SNP,C,A
8,8,TP53,ENST00000269305.4,7579415,7579415,Nonsense_Mutation,SNP,C,T
9,9,TP53,ENST00000269305.4,7577096,7577096,Missense_Mutation,SNP,T,C
10,10,TP53,ENST00000269305.4,7577094,7577094,Missense_Mutation,SNP,G,A
11,11,EGFR,ENST00000275493.2,55249022,55249022,Missense_Mutation,SNP,G,A
12,12,TP53,ENST00000269305.4,7578235,7578235,Missense_Mutation,SNP,T,C
13,13,TP53,ENST00000269305.4,7577539,7577539,Missense_Mutation,SNP,G,A
14,14,TP53,ENST00000269305.4,7578268,7578268,Missense_Mutation,SNP,A,C
15,15,TP53,ENST00000269305.4,7578536,7578536,Missense_Mutation,SNP,T,G
16,16,TP53,ENST00000269305.4,7577068,7577068,Frame_Shift_Del,DEL,G,-

This can be achieved simply by using h2m built-in functions. The sample data used in this section can be found in the [dropbox link]('https://www.dropbox.com/scl/fo/369r665lxot7y66cdsft4/h?rlkey=ofy8hlr1dqq0t0qwp5qhenrsf&dl=0').

#### Read from cBioPortal  
In this format, users simply provide a set of variants with their genome coordinates and reference and alternate alleles, as well as the variant type. This format is compatible with all of the datasets in the cBioPortal, as well as AACR-GENIE. Download the txt mutation data file from such public dataset and then load it as follows:

In [33]:
path_aacr = '/Users/gorkordkx/Desktop/Flab - Drylab/Database/AACR-GENIE/v13.1/data_mutations_extended.txt'
df = h2m.cbio_reader(path_aacr)
df

,index,gene_name_h,tx_id_h,start_h,end_h,type_h,ref_seq_h,alt_seq_h
0,0,KRAS,ENST00000256078.4,25398285,25398285,SNP,C,A
1,1,BRAF,ENST00000288602.6,140453136,140453136,SNP,A,T
2,2,EGFR,ENST00000275493.2,55249071,55249071,SNP,C,T
3,3,TP53,ENST00000269305.4,7577120,7577120,SNP,C,T
4,4,NRAS,ENST00000369535.4,115256529,115256529,SNP,T,C
...,...,...,...,...,...,...,...,...
728842,728842,BCORL1,ENST00000218147.7,129189861,129189861,SNP,T,C
728843,728843,BCORL1,ENST00000218147.7,129189992,129189992,SNP,G,T
728844,728844,PHF6,ENST00000332070.3,133547943,133547943,SNP,G,A
728845,728845,PHF6,ENST00000332070.3,133547964,133547964,SNP,G,T
728846,728846,PHF6,ENST00000332070.3,133551330,133551330,SNP,C,T

#### Read from ClinVar
download a ClinVar vcf.gz file, and choose your desired Variation IDs that you wish to model. These vcf.gz files are available in the Reference Files Dropbox Link (under the clinvar folder) or the more up to date files can be accessed here: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/

In [ ]:
filepath = '/Users/gorkordkx/Desktop/GRCh37_clinvar_20240206.vcf.gz'
variation_ids = [925574, 925434, 926695, 925707, 325626, 1191613, 308061, 361149, 1205375, 208043]
df = h2m.clinvar_reader(filepath, variation_ids)
df

[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '2' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '3' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '4' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '5' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '6' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '8' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '9' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '10' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '11' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '12' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '13' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '14' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '15' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '16' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '17' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '18' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '19' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '20' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '21' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '22' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'X' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'Y' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'MT' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'NT_113889.1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'NT_167222.1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'NW_003315925.1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'NW_003315947.1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'NW_003315950.2' is not defined in the header. (Quick workaround: index the file with tabix.)

   index gene_name_h    start_h      end_h type_h ref_seq_h alt_seq_h
0      0        DVL1    1273425    1273426  Indel        AA         G
1      1        MSH6   48010028   48010028    SNP         G         T
2      2       RRM2B  103218209  103218209    INS         A        AT
3      3       RRM2B  103231051  103231052  Indel        GC        AT
4      4        KRAS   25358662   25358663    DEL        CT         C
5      5        TP53    7571192    7571192    SNP         G         C
6      6        TP53    7571198    7571198    SNP         G         A
7      7        TP53    7571206    7571206    SNP         G         A
8      8        TP53    7571224    7571224    SNP         C         T
9      9        TP53    7572147    7572148    DEL        AG         A

#### Read from GenomAD  
Search a specific gene in GenomAD browser, and download the conlusion csv.

In [35]:
df = h2m.genomad_reader('/Users/gorkordkx/Downloads/gnomAD_v4.0.0_ENSG00000141510_2024_02_07_11_36_03.csv','TP53')
df

      index gene_name_h  start_h    end_h ref_seq_h alt_seq_h type_h
0         0        TP53  7661882  7661882         C         T    SNP
1         1        TP53  7661888  7661888         T         A    SNP
2         2        TP53  7661899  7661899         A         G    SNP
3         3        TP53  7661904  7661904         C         T    SNP
4         4        TP53  7661905  7661905         G         A    SNP
...     ...         ...      ...      ...       ...       ...    ...
2036   2036        TP53  7676665  7676665         C         T    SNP
2037   2037        TP53  7676667  7676667         C         A    SNP
2038   2038        TP53  7676667  7676667         C         T    SNP
2039   2039        TP53  7676668  7676668         T         G    SNP
2040   2040        TP53  7676669  7676669         G         T    SNP

[2041 rows x 7 columns]

### Get canonical transcript ID of human genes if needed, no internet connection needed

There will be returning two dataframes for success and failures.

In [46]:
df = df_sample.drop('tx_id_h', axis = 1)
df

,index,gene_name_h,start_h,end_h,class_h,type_h,ref_seq_h,alt_seq_h
0,0,TP53,7579311,7579311,Splice_Site,SNP,C,A
1,1,KRAS,25398284,25398284,Missense_Mutation,SNP,C,A
2,2,TP53,7577567,7577567,Nonsense_Mutation,SNP,A,T
3,3,KRAS,25398284,25398284,Missense_Mutation,SNP,C,T
4,4,KRAS,25398281,25398281,Missense_Mutation,SNP,C,T
5,5,TP53,7578392,7578392,Missense_Mutation,SNP,C,T
6,6,TP53,7578406,7578406,Missense_Mutation,SNP,C,T
7,7,TP53,7577141,7577141,Missense_Mutation,SNP,C,A
8,8,TP53,7579415,7579415,Nonsense_Mutation,SNP,C,T
9,9,TP53,7577096,7577096,Missense_Mutation,SNP,T,C
10,10,TP53,7577094,7577094,Missense_Mutation,SNP,G,A
11,11,EGFR,55249022,55249022,Missense_Mutation,SNP,G,A
12,12,TP53,7578235,7578235,Missense_Mutation,SNP,T,C
13,13,TP53,7577539,7577539,Missense_Mutation,SNP,G,A
14,14,TP53,7578268,7578268,Missense_Mutation,SNP,A,C
15,15,TP53,7578536,7578536,Missense_Mutation,SNP,T,G
16,16,TP53,7577068,7577068,Frame_Shift_Del,DEL,G,-

In [47]:
df = h2m.get_tx_batch(df,species='h',ver=37)[0]

No error occurs.

In [48]:
df

,index,gene_name_h,start_h,end_h,class_h,type_h,ref_seq_h,alt_seq_h,tx_id_h,ref_genome_h
0,0,TP53,7579311,7579311,Splice_Site,SNP,C,A,ENST00000269305.4,GRCh37
1,1,KRAS,25398284,25398284,Missense_Mutation,SNP,C,A,ENST00000256078.4,GRCh37
2,2,TP53,7577567,7577567,Nonsense_Mutation,SNP,A,T,ENST00000269305.4,GRCh37
3,3,KRAS,25398284,25398284,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37
4,4,KRAS,25398281,25398281,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37
5,5,TP53,7578392,7578392,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37
6,6,TP53,7578406,7578406,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37
7,7,TP53,7577141,7577141,Missense_Mutation,SNP,C,A,ENST00000269305.4,GRCh37
8,8,TP53,7579415,7579415,Nonsense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37
9,9,TP53,7577096,7577096,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37
10,10,TP53,7577094,7577094,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37
11,11,EGFR,55249022,55249022,Missense_Mutation,SNP,G,A,ENST00000275493.2,GRCh37
12,12,TP53,7578235,7578235,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37
13,13,TP53,7577539,7577539,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37
14,14,TP53,7578268,7578268,Missense_Mutation,SNP,A,C,ENST00000269305.4,GRCh37
15,15,TP53,7578536,7578536,Missense_Mutation,SNP,T,G,ENST00000269305.4,GRCh37
16,16,TP53,7577068,7577068,Frame_Shift_Del,DEL,G,-,ENST00000269305.4,GRCh37

### Query mouse orthologous genes

In [49]:
df = h2m.query_batch(df)[0]
df

No error occurs.

,index,gene_name_h,start_h,end_h,class_h,type_h,ref_seq_h,alt_seq_h,tx_id_h,ref_genome_h,gene_name_m
0,11,EGFR,55249022,55249022,Missense_Mutation,SNP,G,A,ENST00000275493.2,GRCh37,Egfr
1,1,KRAS,25398284,25398284,Missense_Mutation,SNP,C,A,ENST00000256078.4,GRCh37,Kras
2,3,KRAS,25398284,25398284,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37,Kras
3,4,KRAS,25398281,25398281,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37,Kras
4,0,TP53,7579311,7579311,Splice_Site,SNP,C,A,ENST00000269305.4,GRCh37,Trp53
5,2,TP53,7577567,7577567,Nonsense_Mutation,SNP,A,T,ENST00000269305.4,GRCh37,Trp53
6,5,TP53,7578392,7578392,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53
7,6,TP53,7578406,7578406,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53
8,7,TP53,7577141,7577141,Missense_Mutation,SNP,C,A,ENST00000269305.4,GRCh37,Trp53
9,8,TP53,7579415,7579415,Nonsense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53
10,9,TP53,7577096,7577096,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37,Trp53
11,10,TP53,7577094,7577094,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37,Trp53
12,12,TP53,7578235,7578235,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37,Trp53
13,13,TP53,7577539,7577539,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37,Trp53
14,14,TP53,7578268,7578268,Missense_Mutation,SNP,A,C,ENST00000269305.4,GRCh37,Trp53
15,15,TP53,7578536,7578536,Missense_Mutation,SNP,T,G,ENST00000269305.4,GRCh37,Trp53
16,16,TP53,7577068,7577068,Frame_Shift_Del,DEL,G,-,ENST00000269305.4,GRCh37,Trp53

### Get canonical transcript ID of mouse genes, no internet connection needed

In [50]:
df = h2m.get_tx_batch(df, species='m')[0]
df

No error occurs.

,index,gene_name_h,start_h,end_h,class_h,type_h,ref_seq_h,alt_seq_h,tx_id_h,ref_genome_h,gene_name_m,tx_id_m
0,11,EGFR,55249022,55249022,Missense_Mutation,SNP,G,A,ENST00000275493.2,GRCh37,Egfr,ENSMUST00000020329.13
1,1,KRAS,25398284,25398284,Missense_Mutation,SNP,C,A,ENST00000256078.4,GRCh37,Kras,ENSMUST00000111710.8
2,3,KRAS,25398284,25398284,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37,Kras,ENSMUST00000111710.8
3,4,KRAS,25398281,25398281,Missense_Mutation,SNP,C,T,ENST00000256078.4,GRCh37,Kras,ENSMUST00000111710.8
4,0,TP53,7579311,7579311,Splice_Site,SNP,C,A,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
5,2,TP53,7577567,7577567,Nonsense_Mutation,SNP,A,T,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
6,5,TP53,7578392,7578392,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
7,6,TP53,7578406,7578406,Missense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
8,7,TP53,7577141,7577141,Missense_Mutation,SNP,C,A,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
9,8,TP53,7579415,7579415,Nonsense_Mutation,SNP,C,T,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
10,9,TP53,7577096,7577096,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
11,10,TP53,7577094,7577094,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
12,12,TP53,7578235,7578235,Missense_Mutation,SNP,T,C,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
13,13,TP53,7577539,7577539,Missense_Mutation,SNP,G,A,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
14,14,TP53,7578268,7578268,Missense_Mutation,SNP,A,C,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
15,15,TP53,7578536,7578536,Missense_Mutation,SNP,T,G,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10
16,16,TP53,7577068,7577068,Frame_Shift_Del,DEL,G,-,ENST00000269305.4,GRCh37,Trp53,ENSMUST00000108658.10

### Batch modeling

In [51]:
import warnings
warnings.filterwarnings("ignore")
result = h2m.model_batch(df, records_h, index_list_h, records_m, index_list_m, db_h, db_m, 37)
result[0]

No error occurs.

,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,ref_seq_h,alt_seq_h,HGVSc_h,HGVSp_h,classification_h,exon_h,type_h,status,class,statement,gene_name_m,gene_id_m,tx_id_m,chr_m,exon_num_m,strand_m,type_m,classification_m,exon_m,start_m_ori,end_m_ori,ref_seq_m_ori,alt_seq_m_ori,HGVSc_m_ori,HGVSp_m_ori,start_m,end_m,ref_seq_m,alt_seq_m,HGVSc_m,HGVSp_m,index
0,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7579311,7579311,C,A,ENST00000269305.4:c.279G>T,None,"Non_Coding,I",None,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,0
1,KRAS,ENSG00000133703.7,ENST00000256078.4,chr12,4,-,True,25398284,25398284,C,A,ENST00000256078.4:c.34G>T,G12V,Missense,E_1,SNP,True,0,Class 0: This mutation can be originally modeled.,Kras,ENSMUSG00000030265.15,ENSMUST00000111710.8,chr6,4,-,SNP,Missense,E_1,145192497.0,145192497.0,C,A,ENSMUST00000111710.8:c.34G>T,G12V,145192497.0,145192497.0,C,A,ENSMUST00000111710.8:c.34G>T,G12V,1
2,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577567,7577567,A,T,ENST00000269305.4:c.713T>A,C238delins*,Nonsense,E_6,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Nonsense,E_6,69480008.0,69480008.0,T,A,ENSMUST00000108658.10:c.704T>A,C235delins*,69480008.0,69480008.0,T,A,ENSMUST00000108658.10:c.704T>A,C235delins*,2
3,KRAS,ENSG00000133703.7,ENST00000256078.4,chr12,4,-,True,25398284,25398284,C,T,ENST00000256078.4:c.34G>A,G12D,Missense,E_1,SNP,True,0,Class 0: This mutation can be originally modeled.,Kras,ENSMUSG00000030265.15,ENSMUST00000111710.8,chr6,4,-,SNP,Missense,E_1,145192497.0,145192497.0,C,T,ENSMUST00000111710.8:c.34G>A,G12D,145192497.0,145192497.0,C,T,ENSMUST00000111710.8:c.34G>A,G12D,3
4,KRAS,ENSG00000133703.7,ENST00000256078.4,chr12,4,-,True,25398281,25398281,C,T,ENST00000256078.4:c.37G>A,G13D,Missense,E_1,SNP,True,0,Class 0: This mutation can be originally modeled.,Kras,ENSMUSG00000030265.15,ENSMUST00000111710.8,chr6,4,-,SNP,Missense,E_1,145192494.0,145192494.0,C,T,ENSMUST00000111710.8:c.37G>A,G13D,145192494.0,145192494.0,C,T,ENSMUST00000111710.8:c.37G>A,G13D,4
5,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578392,7578392,C,T,ENST00000269305.4:c.537G>A,E180K,Missense,E_4,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_4,69479352.0,69479352.0,G,A,ENSMUST00000108658.10:c.528G>A,E177K,69479352.0,69479352.0,G,A,ENSMUST00000108658.10:c.528G>A,E177K,5
6,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578406,7578406,C,T,ENST00000269305.4:c.523G>A,R175H,Missense,E_4,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_4,69479338.0,69479338.0,G,A,ENSMUST00000108658.10:c.514G>A,R172H,69479338.0,69479338.0,G,A,ENSMUST00000108658.10:c.514G>A,R172H,6
7,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577141,7577141,C,A,ENST00000269305.4:c.796G>T,G266V,Missense,E_7,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,7
8,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7579415,7579415,C,T,ENST00000269305.4:c.271G>A,W91delins*,Nonsense,E_3,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,8
9,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577096,7577096,T,C,ENST00000269305.4:c.841A>G,D281G,Missense,E_7,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_7,69480458.0,69480458.0,A,G,ENSMUST00000108658.10:c.832A>G,D278G,69480458.0,69480458.0,A,G,ENSMUST00000108658.10:c.832A>G,D278G,9
10,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577094,7577094,G,A,ENST00000269305.4:c.843C>T,R282W,Missense,E_7,SNP,True,1,Class 1: This mutation can be alternatively mo...,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,ONP,Missense,E_7,69480460.0,69480460.0,C,T,ENSMUST00000108658.10:c.834C>T,R279C,69480460.0,69480462.0,CGC,TGG,ENSMUST00000108658.10:c.834_836CGC>TGG,R279W,10
11,EGFR,ENSG00000146648.11,ENST00000275493.2,chr7,28,+,True,55249022,55249022,G,A,ENST00000275493.2:c.2319G>A,V774M,Missense,E_20,SNP,True,1,Class 1: This mutation can be alternatively mo...,Egfr,ENSMUSG00000020122.17,ENSMUST00000020329.13,chr11,28,+,ONP,Missense,E_20,16846930.0,16846930.0,G,A,ENSMUST00000020329.13:c.2325G>A,V776I,16846930.0,16846932.0,GTA,ATG,ENSMUST00000020329.13:c.2325_2327GTA>ATG,V776M,11
12,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578235,7578235,T,C,ENST00000269305.4:c.613A>G,Y205C,Missense,E_5,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,12
13,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577539,7577539,G,A,ENST00000269305.4:c.741C>T,R248W,Missense,E_6,SNP,True,1,Class 1: This mutation can be alternatively mo...,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,ONP,Missense,E_6,69480036.0,69480036.0,C,T,ENSMUST00000108658.10:c.732C>T,R245C,69480036.0,69480038.0,CGC,TGG,ENSMUST00000108658.10:c.732_734CGC>TGG,R245W,13
14,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578268,7578268,A,C,ENST00000269305.4:c.580T>G,L194R,Missense,E_5,SNP,True,0,Class 0: This mutation can be originally modeled.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,SNP,Missense,E_5,69479473.0,69479473.0,T,G,ENSMUST00000108658.10:c.571T>G,L191R,69479473.0,69479473.0,T,G,ENSMUST00000108658.10:c.571T>G,L191R,14
15,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7578536,7578536,T,G,ENST00000269305.4:c.393A>C,K132Q,Missense,E_4,SNP,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,15
16,TP53,ENSG00000141510.11,ENST00000269305.4,chr17,10,-,True,7577068,7577068,G,,ENST00000269305.4:c.869C>,K291Rfs*54,Frame_Shifting,E_7,DEL,False,4,Class 4: Flanked segments are not identical.,Trp53,ENSMUSG00000059552.14,ENSMUST00000108658.10,chr11,10,+,None,None,None,NaN,NaN,None,None,None,None,NaN,NaN,None,None,None,None,16

# Appendix

## Update History

1.1.0 Jan 16, 2023
- how to get strand_h  
- compatibility of null exonlist  
- compatibility of non-coding mutations  
- add save common canonical tx dicitonaries

1.1.1 Feb 7, 2023
- amino acid function
- batch processing function

## Database Sources

*Local* 
**Dictionaries**   
1. name_dict: Dictionary of human ensembl id to human gene name.  
2. homo_dict: Dictionary of to human gene name to all  (json-like format). (Prepared by using biomart)  
3. human_only_list: List of human-only gene names. (Prepared by using biomart)

**Databases**
1. GENECODE Databases  
- human version 37  
- human version 38  
- mouse  
2. Refgenome
- human version 37  
- human version 38  
- mouse  

*Online*
ENSEMBL API

## Workflow

![workflow](images/workflow.png)

## Functions

### cbio_reader( ):   
- Function
    - Generate h2m input from cbioportal data.  

- Parameter:
    - path (str): the path of mutation data in txt format.
    - keep (bool): True: keep all the original columns in the dataframe/ False: keep the necesssary columns for h2m only. Default to False.  

- Output: 
    - An input dataframe for h2m modeling.

- Example:

In [ ]:
h2m.cbio_reader('.../data_mutations.txt', keep=False)

### clinvar_reader( ):

- Generate h2m input from ClinVar data.  

- Parameter:
    - path (str): the path of clinvar renference vcf.gz data.
    - list_of_ids (list): the list of variation ids.
    - keep (bool): True: keep all the original columns in the dataframe/ False: keep the necesssary columns for h2m only. Default to False.  

- Output: 
    - An input dataframe for h2m modeling.

- Example:

In [ ]:
filepath = '.../GrCh37_clinvar_20230923.vcf.gz'  
variation_ids = [925574, 925434, 926695, 925707, 325626, 1191613, 308061, 361149, 1205375, 208043]   
df = h2m.clinvar_reader(filepath, variation_ids)

### genomad_reader( ):

- Generate h2m input from GenomAD data.  

- Parameter:
    - path (str): the path of GenomAD csv data.
    - gene_name (str): the gene name.
    - keep (bool): True: keep all the original columns in the dataframe/ False: keep the necesssary columns for h2m only. Default to False.  

- Output: 
    - An input dataframe for h2m modeling.

- Example:

In [ ]:
df = h2m.genomad_reader('/Users/gorkordkx/Downloads/gnomAD_v4.0.0_ENSG00000141510_2024_02_07_11_36_03.csv','TP53')
df

### query( )  
- Function  
    -  Query a human gene for the presence of mouse homologs.  
- Parameters   
    - id: string, identification of a human gene. Multiple input forms are accepted, including gene name, stable ensembl gene id with or without version number.  
    - ver (optional): int, specify the version of human, one of 37/38. Only necessary when using human gene ensembl id.  
    -  ty (optional): type of your input id. string, one of *name, gene_id*. Not necessary.  
 show (optional): bool, print summary of output or not.  
- output  
    -  A list of all mouse orthologs (if have; sometimes more than one.) Each element is a dictionary of mouse gene name, mouse gene id, homology type and similarity of human and mouse gene in percentage.  
- Example

In [462]:
h2m.query('TP53')

Query human gene: TP53;
Mouse ortholog(s): Trp53;
Homology type: one2one;
Sequence Simalarity(%):77.3537.

[{'gene_name_m': 'Trp53',
  'gene_id_m': 'ENSMUSG00000059552',
  'homology_type': 'ortholog_one2one',
  'similarity': 77.3537}]

In [465]:
h2m.query('ENSG00000141510')

Query human gene: TP53;
Mouse ortholog(s): Trp53;
Homology type: one2one;
Sequence Simalarity(%):77.3537.

[{'gene_name_m': 'Trp53',
  'gene_id_m': 'ENSMUSG00000059552',
  'homology_type': 'ortholog_one2one',
  'similarity': 77.3537}]

### 3.4 query_batch( )    
- Function  
    - Query a human or mouse gene for coordinate and information of all its transcripts.  

- Parameters   
    - id: string, identification of a human gene. Multiple input forms are accepted, including gene   
    - species: string, ‘h’ for human or ‘m’ for mouse.  
    - name, stable ensembl gene id with or without version number.  
    - ver: int, specify the version of human, one of 37/38. It is a necessary parameter.  
    - ty (optional): type of your input id. string, one of *name, gene_id*.
    - show (optional): bool, print summary of output or not.  
- output  
    - A list [chromosome, start location(of gene), end location(of gene), canonical transcript id, list of all transcript id (the canonical one included and always at the first place), a list of additional information of each transcript]  
- example

In [ ]:
h2m.query_batch(df)

### get_tx( )    
- Function  
    - Query a human or mouse gene for coordinate and information of all its transcripts.  

- Parameters   
    - id: string, identification of a human gene. Multiple input forms are accepted, including gene   
    - species: string, ‘h’ for human or ‘m’ for mouse.  
    - name, stable ensembl gene id with or without version number.  
    - ver: int, specify the version of human, one of 37/38. It is a necessary parameter.  
    - ty (optional): type of your input id. string, one of *name, gene_id*.
    - show (optional): bool, print summary of output or not.  
- output  
    - A list [chromosome, start location(of gene), end location(of gene), canonical transcript id, list of all transcript id (the canonical one included and always at the first place), a list of additional information of each transcript]  
- example

In [11]:
x = h2m.get_tx_id('TP53','h',ver=37)

Genome assembly: GRCh37;
The canonical transcript is: ENST00000269305.4;
You can choose from the 17 transcripts below for further analysis:
(1)ENST00000269305.4 (2)ENST00000413465.2 (3)ENST00000359597.4 (4)ENST00000504290.1 (5)ENST00000510385.1 (6)ENST00000504937.1 (7)ENST00000455263.2 (8)ENST00000420246.2 (9)ENST00000445888.2 (10)ENST00000576024.1 (11)ENST00000509690.1 (12)ENST00000514944.1 (13)ENST00000574684.1 (14)ENST00000505014.1 (15)ENST00000508793.1 (16)ENST00000604348.1 (17)ENST00000503591.1

:

### get_tx_batch( )
- Function:
    - Batch query of canonical transcript IDs of human or mouse genes.

- Parameters:  
    - df (Pandas DataFrame): Must include a column of gene names named 'gene_name_h'/'gene_name_m', depending on the species. An index column is recommended.
    - species (str): 'h' for human or 'm' for mouse.  
    - ver (int): specify the version of human, one of 37/38.

- Return:  
    - Two dataframes. The first dataframe is the processed original dataframe with canonical transcirpt id attached in the column named 'tx_id_h'/'tx_id_m'. Thesecond dataframe contains all rows that are not successfully processed.

- Example:

In [ ]:
h2m.get_tx_batch(df,'h',ver=37)

### model( )  
- Function  
    - Model human variants in the mouse genome.  

- Workflow  

![model_workflow](images/model_workflow.png)  

- Original modeling with uncertain effects:  
![original_uncertain](images/original_uncertain.png)  

- Alternative modeling with uncertain effects:  
![alternative](images/alternative.png)  

- All possible status:  
![status](images/status.png)  

- Parameters   
    - records_h, index_list_h, records_m, index_list_m: human and mouse reference genome.  
    - db_h, db_m: human and mouse GENCODE annotation.  
    - tx_id_h, tx_id_m: human and mouse transcript id (could get by **h2m.get_tx_id()**).  
    - start_h, end_h: int, start and end location of the mutation on the chromosome.  
    - alt_seq_h: str, human mutation alternative sequence.  
    - ty_h: str, human variantion type. One of ['SNP', 'DNP', 'ONP', 'INS', 'DEL'].  
    - ver: int, human ref genome number. 37 or 38.  
    - ref_seq_h (optional): str, human mutation reference sequence.    
    - param (optional): set param = 'BE' and will only output base editing modelable results.  
    - search_alternative (optional): set search_alternative = False and will only output original modeling results.  
    - max_alternative (optional): the maximum number of output alternatives of one human variants.  
    - nonstop_size (optional): the length of neucleotides that are included after the stop codon for alignment and translation in case of the nonstop mutations or frame shifting mutations.  
    - flank_size (optional): the number of amino acids or neucleotides (for non-coding mutations) that are included on each side of the mutation site.  
    - splicing_size (optional): 
    - batch (optional): set batch = True and will use input align_dict to save time in batch processing.  
    - show_sequence (optional): set batch = True and will output the whole sequences.  
    - align_dict (optional): input a prepared dictionary of alignment indexes to save time in batch processing.  
    - memory_protect (optional): default True. Break long alignments that may lead to death of the kernel.    
    - memory_size (optional): maxlength of aligned sequence when memory_protect == True.  

- output  
    - a dictionary or a list of dictionaries that include comprehensive information for the human and mouse variants.  

- Other rules  
    1. If the mutation falls in the coding and non-coding regions at the same time, it would be considered and processed as a ORIGIAL-MODELING ONLY mutation.
    3. The alt_seq input should be in the positive strand and the start_h coordinate should be smaller than or equal the end_h coordinate.
    4. If the ref-seq or alt-see has no length, it could be input as ‘’ or ‘-’.

- example

In [32]:
tx_id_h, tx_id_m = list_tx_id_h[3], list_tx_id_m[3]
# use the canonical transcript
model_result = h2m.model(records_h,index_list_h, records_m, index_list_m, db_h, db_m, tx_id_h, tx_id_m, 7577120, 7577120, 'T', ty_h = 'SNP', ver = 37)
model_result

{'gene_name_h': 'TP53',
 'gene_id_h': 'ENSG00000141510.11',
 'tx_id_m': 'ENSMUST00000108658.10',
 'chr_h': 'chr17',
 'exon_num_h': 10,
 'strand_h': '-',
 'start_h': 7577120,
 'end_h': 7577120,
 'ref_seq_h': 'C',
 'alt_seq_h': 'T',
 'HGVSp_h': 'R273H',
 'classification_h': 'Missense',
 'classification_h_detail': None,
 'exon_h': 'E_7',
 'type_h': 'SNP',
 'status': True,
 'error': 0,
 'statement': 'This mutation can be originally modeled.',
 'gene_name_m': 'Trp53',
 'gene_id_m': 'ENSMUSG00000059552.14',
 'chr_m': 'chr11',
 'exon_num_m': 10,
 'strand_m': '+',
 'type_m': 'SNP',
 'classification_m': 'Missense',
 'exon_m': 'E_7',
 'start_m_ori': 69480434,
 'end_m_ori': 69480434,
 'ref_seq_m_ori': 'G',
 'alt_seq_m_ori': 'A',
 'HGVSp_m_ori': 'R270H',
 'start_m': 69480434,
 'end_m': 69480434,
 'ref_seq_m': 'G',
 'alt_seq_m': 'A',
 'HGVSp_m': 'R270H'}

### model_batch( )
- Function:
    - Batch modeling of human variants in the mouse genome.  

- Parameters:  
    - df (Pandas DataFrame): Must include columns {'start_h','end_h','type_h','ref_seq_h','alt_seq_h','tx_id_h','tx_id_m','index'}.
    - ecords_h, index_list_h, records_m, index_list_m: reference genome files
    - db_h, db_m: genomic annotation files
    - ver (int): specify the version of human, one of 37/38.
    - param (optional): set param = 'BE' and will only output base editing modelable results.  
    - coor (optional): default = 'nc'. set input = 'aa' and will be compatable with input of amino acid variants.
    - search_alternative (optional): set search_alternative = False and will only output original modeling results.  
    - max_alternative (optional): the maximum number of output alternatives of one human variants.  
    - nonstop_size (optional): the length of neucleotides that are included after the stop codon for alignment and translation in case of the nonstop mutations orframe shifting mutations.  
    - flank_size (optional): the number of amino acids or neucleotides (for non-coding mutations) that are included on each side of the mutation site.  
    - splicing_size (optional): 
    - batch (optional): set batch = True and will use input align_dict to save time in batch processing.  
    - show_sequence (optional): set batch = True and will output the whole sequences.  
    - align_dict (optional): input a prepared dictionary of alignment indexes to save time in batch processing.  
    - memory_protect (optional): default True. Break long alignments that may lead to death of the kernel.    
    - memory_size (optional): maxlength of aligned sequence when memory_protect == True.  

- Return:  
    - Two dataframes. The first dataframe is the processed original dataframe. The second dataframe contains all rows that are not successfully processed.

- Example:

In [ ]:
h2m.model_batch(df, records_h, index_list_h, records_m, index_list_m, db_h, db_m, ver = 37, param = 'BE')